### ISSUE TITLE
api_key value not recognized

### ISSUE THREAD

**Issue by lsm5** [sclorg/testing-farm-as-github-action#122]
### Container platform

Podman/Docker

### Description

I have created a github action at https://github.com/containers/podman/pull/21335/files#diff-2ecd1faf0eac3d817fb0066c8145e331c54aadf84bb9fd09ca6788028b3b8a9fR12-R18 and also set TF_API_KEY in the repo's secrets . But api_key isn't being recognized https://github.com/containers/podman/actions/runs/8081285320/job/22079487386?pr=21335 . Hope this is the right place to report it.

**Comment by zmiklank** [comment]
Hi, this is expected, and not related to testing-farm-as-github-action, but rather to GitHub Actions in general.
More information can be found in this article:
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

Following paragraph is copied from this article:
"Due to the dangers inherent to automatic processing of PRs, GitHub’s standard pull_request workflow trigger by default prevents write permissions and secrets access to the target repository. However, in some scenarios such access is needed to properly process the PR. To this end the pull_request_target workflow trigger was introduced."
