### ISSUE TITLE
Some long string (e.g. base64) github secrets can't be correctly passed to tmt.

### ISSUE THREAD

**Issue by henrywang** [sclorg/testing-farm-as-github-action#152]
The new `v2`, some long string (like base64 string) github secrets can't be correctly passed to tmt. Like some B64 strings:
```
base64: invalid input
base64: invalid input
mv: cannot move '/tmp/tmp.66DLb9AKEw/client.conf' to '/etc/beaker/client.conf': No such file or directory
base64: invalid input
```

**Comment by henrywang** [comment]
Does anyone can help on this? Without this fix, we can't upgrade to v2 from v1. Thanks.

**Comment by zmiklank** [comment]
Hi @henrywang, our time is currently somehow limited. This bug is related to a specific usecase and does not seem to be influencing many users. Therefore we do not assign high priority to it.

Contributions are welcomed here.

We will get to this eventually, but I cannot unfortunately promise you some specific date.

**Comment by phracek** [comment]
@henrywang How do you pass the long string? Do you have a log for it? Thanks. I would like to get a picture, whether the problem is in our action, or in the testing farm itself.
